" Filetype
filetype plugin on
filetype indent on
set nocompatible

" Plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
" Color scheme
Plugin 'arcticicestudio/nord-vim'
" Airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Language
Plugin 'fatih/vim-go'
Plugin 'ludovicchabant/vim-gutentags'
" Git
Plugin 'airblade/vim-gitgutter'
" Navigation
Plugin 'christoomey/vim-tmux-navigator'
call vundle#end()

" Colors
syntax on
syntax enable
set background=dark
if exists('+termguicolors')
   let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
   let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
   set termguicolors
endif
set t_Co=256
colorscheme nord
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE

" Options
set cursorline
set number
set expandtab
set shiftwidth=4
set tabstop=4
set backspace=eol,indent,start
set colorcolumn=100
set textwidth=100
set autoindent
set viminfo='20,<1000,s1000
set hidden
" Display buffer names
set modelines=1
" Disable search highlights
set nohlsearch
" Backup options
set directory^=$HOME/.vim/tmp/
set backupdir^=$HOME/.vim/tmp/
set undodir^=$HOME/.vim/undo/
set nobackup
set nowritebackup
set undofile
set backup
set formatoptions+=rn

" Wrapping lines without 2 spaces
set nojs

" Speed up syntax matching
set re=1

" Proposition when tabbing
set wildmode=longest,list,full
set wildmenu
match Error /\s\+$/
set shortmess+=T
set cmdheight=2

" Vim last position
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Tmux
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Leader
let mapleader=","

" Maps
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev X x

" Buffer navigation
nmap <leader>l :bnext<CR>
nmap <leader>h :bprev<CR>
nmap <leader>q :bp <BAR> bw #<CR>
nmap <leader>b :ls<CR>:b<space>

" Airline
let g:airline_theme='nord'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tabs = 0
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#bufferline#enabled = 1

" Nord color scheme
let g:nord_cursor_line_number_background = 1

" Vim go
let g:go_highlight_functions = 1
let g:go_fmt_autosave = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"

" INFRA-9620 / CVE-2019-06-04
" Please leave this as the LAST LINE in your .vimrc
" This is a temporary kludge fix until Apple updates bundled vim package
" <Infra
set nomodeline
